### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by bggold** [vinaooo/Ubuntu-Font-Vinaooo#1]
I downloaded your module and get an unzip error when trying to install.

Interested in trying it out.

Thanks

**Comment by petitfella** [comment]
I also went through the same problem.  Downloaded from Github and Fox Manager.

**Comment by vinaooo** [comment]
Thanks

i'm looking into it, can you share a print from this error?

ps: if you are using the most recent version of Fox Manager, the app has an error installing any modulo to me
ps2: I got the error, i'm solving it now

**Comment by vinaooo** [comment]
Fixed, it's on my github, please test it

Thank you
